# docker-compose.yml
version: '3.8'

services:
  dst-master:
    build: . # Builds the image from the Dockerfile in the current directory
    container_name: dst_master_server
    user: steam # Runs the container with this user (must match the user in Dockerfile)
    restart: unless-stopped
    ports:
      - "10999:10999/udp" # Host UDP 10999 -> Container UDP 10999
    volumes:
      # Mount the host directory for server configuration (.ini, token) and save files.
      # This includes cluster.ini, cluster_token.txt, and MOST IMPORTANTLY modoverrides.lua
      # for direct access from the host machine.
      - ./dst_data:/home/steam/.klei

      # Mount a named volume for Don't Starve Together server files (game engine, mods, etc.)
      # to make them persistent. Even if the container is restarted or the image is updated,
      # the downloaded server files and mods will be preserved.
      - dst_server_data:/home/steam/dst_server
    command: ["/home/steam/start_master.sh"] # Runs the script that starts the Master shard
    tty: true # Allocates a pseudo-TTY (helpful for interactive console use)
    stdin_open: true # Keeps stdin open
    environment: # Required environment variables for the scripts to run properly
      - STEAM_USER=steam
      - DST_SERVER_DIR=/home/steam/dst_server
      - DST_CLUSTER_NAME=MyDediServer # Must match the folder name inside ./dst_data

  dst-caves:
    build: . # Uses the same image as the master
    container_name: dst_caves_server
    user: steam
    restart: unless-stopped
    ports:
      - "11000:11000/udp" # Host UDP 11000 -> Container UDP 11000
    volumes:
      # Mount the SAME host directory for configuration and save files so both shards can share them.
      - ./dst_data:/home/steam/.klei

      # Mount the SAME named volume for server files.
      - dst_server_data:/home/steam/dst_server
    command: ["/home/steam/start_caves.sh"] # Runs the script that starts the Caves shard
    depends_on: # Optional: waits for the master service to start (does not guarantee readiness)
      - dst-master
    tty: true
    stdin_open: true
    environment: # Required environment variables for the scripts to run properly
      - STEAM_USER=steam
      - DST_SERVER_DIR=/home/steam/dst_server
      - DST_CLUSTER_NAME=MyDediServer # Must match the folder name inside ./dst_data

# Named Volume Definition
# This volume stores DST server files and downloaded mods under Docker's managed space.
# Direct access from the host might be a bit harder, but this avoids permission issues
# and ensures cleaner Docker management.
volumes:
  dst_server_data:
    driver: local # Uses the default local driver
