services:
  dst-master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dst-master
    volumes:
      - ./dst_data/DoNotStarveTogether:/home/dst/.klei/DoNotStarveTogether
      - dst-server:/home/dst/server
    ports:
      - "10999:10999/udp"
      - "27018:27018/udp"
      - "10889:10889/udp"
    environment:
      - SHARD_NAME=Master
      - SERVER_PORT=10999
      - MASTER_SERVER_PORT=27018
      - AUTHENTICATION_PORT=8768
      - IS_MASTER=true
      - CLUSTER_NAME=MyDediServer
    restart: unless-stopped
    networks:
      - dst-network

  dst-caves:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dst-caves
    volumes:
      - ./dst_data/DoNotStarveTogether:/home/dst/.klei/DoNotStarveTogether
      - dst-server:/home/dst/server
    ports:
      - "11000:11000/udp"
      - "27019:27019/udp"
    environment:
      - SHARD_NAME=Caves
      - SERVER_PORT=11000
      - MASTER_SERVER_PORT=27019
      - AUTHENTICATION_PORT=8769
      - IS_MASTER=false
      - CLUSTER_NAME=MyDediServer
    restart: unless-stopped
    depends_on:
      - dst-master
    networks:
      - dst-network

volumes:
  dst-server:

networks:
  dst-network:
    driver: bridge
